version: "3"
services:
  device-daemon:
    container_name: iot-device-daemon-container
    build: ./device-daemon
    privileged: true
    ports:
      - "3000:22"
      - "4000:80"
      - "5000:3000"
      - "6000:8000"
    environment:
      - NOTIFICATIONS_ENDPOINT=XXXXX
      - NOTIFICATIONS_API_KEY
    volumes:
      - ./device-daemon:/device-daemon

  alerts-service:
    container_name: notifications-service-container
    build: ./sms-notifications
    ports:
      - "7000:5000"
    volumes:
      - ./sms-notifications:/sms-notifications
    environment:
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
      - REMOTEIT_PASSWORD
      - REMOTEIT_USERNAME
      - REMOTEIT_DEVELOPER_KEY
      - REMOTEIT_DEVICE_ADDRESS
